apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gitops-repo
  namespace: gitops-control
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - git:
      repoURL: https://github.com/ankur512512/gitops-infra-repo.git
      branch: main
      includePaths:
      - apps/gitops-app/base
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      strictSemvers: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: gitops-control
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/ankur512512/gitops-infra-repo.git
          checkout:
          - branch: main
            path: out
      - uses: kustomize-set-image
        config:
          path: out/apps/gitops-app/overlays/dev
          images:
          - image: nginx
      - uses: git-commit
        config:
          path: out
          message: "Promoted to dev"
      - uses: git-push
        config:
          path: out
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: gitops-control
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/ankur512512/gitops-infra-repo.git
          checkout:
          - branch: main
            path: out
      - uses: kustomize-set-image
        config:
          path: out/apps/gitops-app/overlays/stage
          images:
          - image: nginx
      - uses: git-commit
        config:
          path: out
          message: "Promoted to stage"
      - uses: git-push
        config:
          path: out
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: gitops-control
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      stages:
      - stage
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/ankur512512/gitops-infra-repo.git
          checkout:
          - branch: main
            path: out
      - uses: kustomize-set-image
        config:
          path: out/apps/gitops-app/overlays/prod
          images:
          - image: nginx
      - uses: git-commit
        config:
          path: out
          message: "Promoted to prod"
      - uses: git-push
        config:
          path: out
