apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gitops-repo
  namespace: gitops-control
spec:
  project: gitops-control
  subscriptions:
  - git:
      repoURL: https://github.com/ankur512512/gitops-infra-repo.git
      branch: main
      directories:
      - apps/gitops-app/base
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: gitops-control
spec:
  project: gitops-control
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/ankur512512/gitops-infra-repo.git
      writeBranch: main
      kustomize:
        images:
        - image: nginx
          path: apps/gitops-app/overlays/dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: gitops-control
spec:
  project: gitops-control
  subscriptions:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      stages:
      - dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/ankur512512/gitops-infra-repo.git
      writeBranch: main
      kustomize:
        images:
        - image: nginx
          path: apps/gitops-app/overlays/stage
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: gitops-control
spec:
  project: gitops-control
  subscriptions:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: gitops-repo
    sources:
      stages:
      - stage
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/ankur512512/gitops-infra-repo.git
      writeBranch: main
      kustomize:
        images:
        - image: nginx
          path: apps/gitops-app/overlays/prod
