apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-dev
images:
- name: ghcr.io/ankur512512/gitops-app-repo
  newTag: sha-0db4275b9ed49f691bacf87f53de5332a4c54f54
