apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-dev
images:
- name: ghcr.io/ankur512512/gitops-app-repo
  newTag: sha-2695aef9c069c1ddfc5d7710cf9418b53e7a1fed
