apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-dev
images:
- name: ghcr.io/ankur512512/gitops-app-repo
  newTag: sha-229b2176ed36a753f0399f8098c0d2ef2c4e9491
