apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: default
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "argocd.ankur.theworkpc.com" # One of them must be CN
  dnsNames:
  - "argocd.ankur.theworkpc.com"
  - "kargo.ankur.theworkpc.com"
