apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: gitops
  namespace: gitops
spec:
#   credentials:
#     git:
#       - repoURL: https://github.com/ankur512512/gitops-infra-repo.git
#         secretRef:
#           name: kargo-git-credentials
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: stage
      autoPromotionEnabled: true
    - stage: prod
      autoPromotionEnabled: false
