apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gitops-app
  namespace: gitops
spec:
  interval: 5m0s
  subscriptions:
    - image:
        repoURL: ghcr.io/ankur512512/gitops-app-repo
        imageSelectionStrategy: NewestBuild
        allowTags: ^sha-[0-9a-f]{7}$
        strictSemvers: false
        discoveryLimit: 20
