apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: update-image-tag
            vars:
              - name: stageName
                value: dev
              - name: overlayPath
                value: apps/gitops-app/overlays/dev
              - name: argoApp
                value: gitops-app-dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: update-image-tag
            vars:
              - name: stageName
                value: stage
              - name: overlayPath
                value: apps/gitops-app/overlays/stage
              - name: argoApp
                value: gitops-app-stage
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        stages:
          - stage
  promotionTemplate:
    spec:
      steps:
        - task:
            name: update-image-tag
            vars:
              - name: stageName
                value: prod
              - name: overlayPath
                value: apps/gitops-app/overlays/prod
              - name: argoApp
                value: gitops-app-prod
