apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: stageName
          value: dev
        - name: overlayPath
          value: apps/gitops-app/overlays/dev
        - name: argoApp
          value: gitops-app-dev
      steps:
        - task:
            name: update-image-tag
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      vars:
        - name: stageName
          value: stage
        - name: overlayPath
          value: apps/gitops-app/overlays/stage
        - name: argoApp
          value: gitops-app-stage
      steps:
        - task:
            name: update-image-tag
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: gitops
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-app
      sources:
        stages:
          - stage
  promotionTemplate:
    spec:
      vars:
        - name: stageName
          value: prod
        - name: overlayPath
          value: apps/gitops-app/overlays/prod
        - name: argoApp
          value: gitops-app-prod
      steps:
        - task:
            name: update-image-tag
