apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: update-image-tag-dev
  namespace: gitops
spec:
  vars:
    - name: gitRepo
      value: https://github.com/ankur512512/gitops-infra-repo.git
    - name: imageRepo
      value: ghcr.io/ankur512512/gitops-app-repo
    - name: overlayPath
      value: apps/gitops-app/overlays/dev
    - name: argoApp
      value: gitops-app-dev
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
          - branch: main
        path: ./repo
    - uses: kustomize-set-image
      config:
        path: ./repo/${{ vars.overlayPath }}
        images:
          - image: ${{ vars.imageRepo }}
            # Use the Freight image tag from the Warehouse
            newTag: ${{ freight.images[vars.imageRepo].tag }}
    - uses: git-commit
      config:
        path: ./repo
        message: "dev: promote to ${{ freight.images[vars.imageRepo].tag }}"
    - uses: git-push
      config:
        path: ./repo
    - uses: argocd-update
      config:
        apps:
          - name: ${{ vars.argoApp }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: update-image-tag-stage
  namespace: gitops
spec:
  vars:
    - name: gitRepo
      value: https://github.com/ankur512512/gitops-infra-repo.git
    - name: imageRepo
      value: ghcr.io/ankur512512/gitops-app-repo
    - name: overlayPath
      value: apps/gitops-app/overlays/stage
    - name: argoApp
      value: gitops-app-stage
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
          - branch: main
        path: ./repo
    - uses: kustomize-set-image
      config:
        path: ./repo/${{ vars.overlayPath }}
        images:
          - image: ${{ vars.imageRepo }}
            newTag: ${{ freight.images[vars.imageRepo].tag }}
    - uses: git-commit
      config:
        path: ./repo
        message: "stage: promote to ${{ freight.images[vars.imageRepo].tag }}"
    - uses: git-push
      config:
        path: ./repo
    - uses: argocd-update
      config:
        apps:
          - name: ${{ vars.argoApp }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: update-image-tag-prod
  namespace: gitops
spec:
  vars:
    - name: gitRepo
      value: https://github.com/ankur512512/gitops-infra-repo.git
    - name: imageRepo
      value: ghcr.io/ankur512512/gitops-app-repo
    - name: overlayPath
      value: apps/gitops-app/overlays/prod
    - name: argoApp
      value: gitops-app-prod
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
          - branch: main
        path: ./repo
    - uses: kustomize-set-image
      config:
        path: ./repo/${{ vars.overlayPath }}
        images:
          - image: ${{ vars.imageRepo }}
            newTag: ${{ freight.images[vars.imageRepo].tag }}
    - uses: git-commit
      config:
        path: ./repo
        message: "prod: promote to ${{ freight.images[vars.imageRepo].tag }}"
    - uses: git-push
      config:
        path: ./repo
    - uses: argocd-update
      config:
        apps:
          - name: ${{ vars.argoApp }}
